<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace cbdesk\eBaySDK\MerchantData\Types;

/**
 *
 * @property \cbdesk\eBaySDK\MerchantData\Types\ActiveInventoryReportResponseType $ActiveInventoryReport
 * @property \cbdesk\eBaySDK\MerchantData\Types\AddFixedPriceItemResponseType[] $AddFixedPriceItemResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\AddItemResponseType[] $AddItemResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\EndFixedPriceItemResponseType[] $EndFixedPriceItemResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\EndItemResponseType[] $EndItemResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\FeeSettlementReportResponseType $FeeSettlementReport
 * @property \cbdesk\eBaySDK\MerchantData\Types\OrderAckResponseType[] $OrderAckResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\RelistFixedPriceItemResponseType[] $RelistFixedPriceItemResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\RelistItemResponseType[] $RelistItemResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\ReviseFixedPriceItemResponseType[] $ReviseFixedPriceItemResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\ReviseInventoryStatusResponseType[] $ReviseInventoryStatusResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\ReviseItemResponseType[] $ReviseItemResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\SetShipmentTrackingInfoResponseType[] $SetShipmentTrackingInfoResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\SoldReportResponseType $SoldReport
 * @property \cbdesk\eBaySDK\MerchantData\Types\UploadSiteHostedPicturesResponseType[] $UploadSiteHostedPicturesResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\VerifyAddFixedPriceItemResponseType[] $VerifyAddFixedPriceItemResponse
 * @property \cbdesk\eBaySDK\MerchantData\Types\VerifyAddItemResponseType[] $VerifyAddItemResponse
 */
class BulkDataExchangeResponsesType extends \cbdesk\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'ActiveInventoryReport' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\ActiveInventoryReportResponseType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ActiveInventoryReport'
        ],
        'AddFixedPriceItemResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AddFixedPriceItemResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'AddFixedPriceItemResponse'
        ],
        'AddItemResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AddItemResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'AddItemResponse'
        ],
        'EndFixedPriceItemResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\EndFixedPriceItemResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'EndFixedPriceItemResponse'
        ],
        'EndItemResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\EndItemResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'EndItemResponse'
        ],
        'FeeSettlementReport' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\FeeSettlementReportResponseType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FeeSettlementReport'
        ],
        'OrderAckResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\OrderAckResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'OrderAckResponse'
        ],
        'RelistFixedPriceItemResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\RelistFixedPriceItemResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'RelistFixedPriceItemResponse'
        ],
        'RelistItemResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\RelistItemResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'RelistItemResponse'
        ],
        'ReviseFixedPriceItemResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\ReviseFixedPriceItemResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ReviseFixedPriceItemResponse'
        ],
        'ReviseInventoryStatusResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\ReviseInventoryStatusResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ReviseInventoryStatusResponse'
        ],
        'ReviseItemResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\ReviseItemResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ReviseItemResponse'
        ],
        'SetShipmentTrackingInfoResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\SetShipmentTrackingInfoResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'SetShipmentTrackingInfoResponse'
        ],
        'SoldReport' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\SoldReportResponseType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SoldReport'
        ],
        'UploadSiteHostedPicturesResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\UploadSiteHostedPicturesResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'UploadSiteHostedPicturesResponse'
        ],
        'VerifyAddFixedPriceItemResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\VerifyAddFixedPriceItemResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'VerifyAddFixedPriceItemResponse'
        ],
        'VerifyAddItemResponse' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\VerifyAddItemResponseType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'VerifyAddItemResponse'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'BulkDataExchangeResponses';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
