<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace cbdesk\eBaySDK\MerchantData\Types;

/**
 *
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $AmountPaid
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $AdjustmentAmount
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $ConvertedAdjustmentAmount
 * @property \cbdesk\eBaySDK\MerchantData\Types\UserType $Buyer
 * @property \cbdesk\eBaySDK\MerchantData\Types\ShippingDetailsType $ShippingDetails
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $ConvertedAmountPaid
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $ConvertedTransactionPrice
 * @property \DateTime $CreatedDate
 * @property \cbdesk\eBaySDK\MerchantData\Enums\DepositTypeCodeType $DepositType
 * @property \cbdesk\eBaySDK\MerchantData\Types\ItemType $Item
 * @property integer $QuantityPurchased
 * @property \cbdesk\eBaySDK\MerchantData\Types\TransactionStatusType $Status
 * @property string $TransactionID
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $TransactionPrice
 * @property boolean $BestOfferSale
 * @property integer $VATPercent
 * @property \cbdesk\eBaySDK\MerchantData\Types\ExternalTransactionType[] $ExternalTransaction
 * @property \cbdesk\eBaySDK\MerchantData\Types\SellingManagerProductDetailsType $SellingManagerProductDetails
 * @property \cbdesk\eBaySDK\MerchantData\Types\ShippingServiceOptionsType $ShippingServiceSelected
 * @property \cbdesk\eBaySDK\MerchantData\Enums\PaidStatusCodeType $BuyerPaidStatus
 * @property \cbdesk\eBaySDK\MerchantData\Enums\PaidStatusCodeType $SellerPaidStatus
 * @property \DateTime $PaidTime
 * @property \DateTime $ShippedTime
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $TotalPrice
 * @property \cbdesk\eBaySDK\MerchantData\Types\FeedbackInfoType $FeedbackLeft
 * @property \cbdesk\eBaySDK\MerchantData\Types\FeedbackInfoType $FeedbackReceived
 * @property \cbdesk\eBaySDK\MerchantData\Types\OrderType $ContainingOrder
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $FinalValueFee
 * @property \cbdesk\eBaySDK\MerchantData\Types\ListingCheckoutRedirectPreferenceType $ListingCheckoutRedirectPreference
 * @property \cbdesk\eBaySDK\MerchantData\Types\RefundArrayType $RefundArray
 * @property \cbdesk\eBaySDK\MerchantData\Enums\SiteCodeType $TransactionSiteID
 * @property \cbdesk\eBaySDK\MerchantData\Enums\TransactionPlatformCodeType $Platform
 * @property string $CartID
 * @property boolean $SellerContactBuyerByEmail
 * @property string $PayPalEmailAddress
 * @property string $PaisaPayID
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $BuyerGuaranteePrice
 * @property \cbdesk\eBaySDK\MerchantData\Types\VariationType $Variation
 * @property string $BuyerCheckoutMessage
 * @property \cbdesk\eBaySDK\MerchantData\Types\TaxesType $Taxes
 * @property boolean $BundlePurchase
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $ActualShippingCost
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $ActualHandlingCost
 * @property string $OrderLineItemID
 * @property string $eBayPaymentID
 * @property \cbdesk\eBaySDK\MerchantData\Types\PaymentHoldDetailType $PaymentHoldDetails
 * @property \cbdesk\eBaySDK\MerchantData\Types\SellerDiscountsType $SellerDiscounts
 * @property string $CodiceFiscale
 * @property boolean $IsMultiLegShipping
 * @property \cbdesk\eBaySDK\MerchantData\Types\MultiLegShippingDetailsType $MultiLegShippingDetails
 * @property \DateTime $InvoiceSentTime
 * @property \cbdesk\eBaySDK\MerchantData\Types\UnpaidItemType $UnpaidItem
 * @property boolean $IntangibleItem
 * @property \cbdesk\eBaySDK\MerchantData\Types\PaymentsInformationType $MonetaryDetails
 * @property \cbdesk\eBaySDK\MerchantData\Types\PickupDetailsType $PickupDetails
 * @property \cbdesk\eBaySDK\MerchantData\Types\PickupMethodSelectedType $PickupMethodSelected
 * @property \cbdesk\eBaySDK\MerchantData\Types\AmountType $ShippingConvenienceCharge
 * @property string $LogisticsPlanType
 * @property \cbdesk\eBaySDK\MerchantData\Types\BuyerPackageEnclosuresType $BuyerPackageEnclosures
 * @property string $InventoryReservationID
 * @property string $ExtendedOrderID
 * @property boolean $eBayPlusTransaction
 * @property \cbdesk\eBaySDK\MerchantData\Types\GiftSummaryType $GiftSummary
 * @property \cbdesk\eBaySDK\MerchantData\Types\DigitalDeliverySelectedType $DigitalDeliverySelected
 * @property boolean $Gift
 * @property boolean $GuaranteedShipping
 */
class TransactionType extends \cbdesk\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'AmountPaid' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AmountPaid'
        ],
        'AdjustmentAmount' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'AdjustmentAmount'
        ],
        'ConvertedAdjustmentAmount' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConvertedAdjustmentAmount'
        ],
        'Buyer' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\UserType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Buyer'
        ],
        'ShippingDetails' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\ShippingDetailsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingDetails'
        ],
        'ConvertedAmountPaid' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConvertedAmountPaid'
        ],
        'ConvertedTransactionPrice' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ConvertedTransactionPrice'
        ],
        'CreatedDate' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CreatedDate'
        ],
        'DepositType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DepositType'
        ],
        'Item' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\ItemType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Item'
        ],
        'QuantityPurchased' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'QuantityPurchased'
        ],
        'Status' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\TransactionStatusType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Status'
        ],
        'TransactionID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TransactionID'
        ],
        'TransactionPrice' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TransactionPrice'
        ],
        'BestOfferSale' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BestOfferSale'
        ],
        'VATPercent' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'VATPercent'
        ],
        'ExternalTransaction' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\ExternalTransactionType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ExternalTransaction'
        ],
        'SellingManagerProductDetails' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\SellingManagerProductDetailsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellingManagerProductDetails'
        ],
        'ShippingServiceSelected' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\ShippingServiceOptionsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingServiceSelected'
        ],
        'BuyerPaidStatus' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BuyerPaidStatus'
        ],
        'SellerPaidStatus' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellerPaidStatus'
        ],
        'PaidTime' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaidTime'
        ],
        'ShippedTime' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippedTime'
        ],
        'TotalPrice' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TotalPrice'
        ],
        'FeedbackLeft' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\FeedbackInfoType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FeedbackLeft'
        ],
        'FeedbackReceived' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\FeedbackInfoType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FeedbackReceived'
        ],
        'ContainingOrder' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\OrderType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ContainingOrder'
        ],
        'FinalValueFee' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FinalValueFee'
        ],
        'ListingCheckoutRedirectPreference' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\ListingCheckoutRedirectPreferenceType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ListingCheckoutRedirectPreference'
        ],
        'RefundArray' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\RefundArrayType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RefundArray'
        ],
        'TransactionSiteID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TransactionSiteID'
        ],
        'Platform' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Platform'
        ],
        'CartID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CartID'
        ],
        'SellerContactBuyerByEmail' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellerContactBuyerByEmail'
        ],
        'PayPalEmailAddress' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PayPalEmailAddress'
        ],
        'PaisaPayID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaisaPayID'
        ],
        'BuyerGuaranteePrice' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BuyerGuaranteePrice'
        ],
        'Variation' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\VariationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Variation'
        ],
        'BuyerCheckoutMessage' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BuyerCheckoutMessage'
        ],
        'Taxes' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\TaxesType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Taxes'
        ],
        'BundlePurchase' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BundlePurchase'
        ],
        'ActualShippingCost' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ActualShippingCost'
        ],
        'ActualHandlingCost' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ActualHandlingCost'
        ],
        'OrderLineItemID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'OrderLineItemID'
        ],
        'eBayPaymentID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayPaymentID'
        ],
        'PaymentHoldDetails' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\PaymentHoldDetailType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentHoldDetails'
        ],
        'SellerDiscounts' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\SellerDiscountsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'SellerDiscounts'
        ],
        'CodiceFiscale' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CodiceFiscale'
        ],
        'IsMultiLegShipping' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'IsMultiLegShipping'
        ],
        'MultiLegShippingDetails' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\MultiLegShippingDetailsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MultiLegShippingDetails'
        ],
        'InvoiceSentTime' => [
            'type' => 'DateTime',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InvoiceSentTime'
        ],
        'UnpaidItem' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\UnpaidItemType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'UnpaidItem'
        ],
        'IntangibleItem' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'IntangibleItem'
        ],
        'MonetaryDetails' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\PaymentsInformationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'MonetaryDetails'
        ],
        'PickupDetails' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\PickupDetailsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PickupDetails'
        ],
        'PickupMethodSelected' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\PickupMethodSelectedType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PickupMethodSelected'
        ],
        'ShippingConvenienceCharge' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ShippingConvenienceCharge'
        ],
        'LogisticsPlanType' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'LogisticsPlanType'
        ],
        'BuyerPackageEnclosures' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\BuyerPackageEnclosuresType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BuyerPackageEnclosures'
        ],
        'InventoryReservationID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'InventoryReservationID'
        ],
        'ExtendedOrderID' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ExtendedOrderID'
        ],
        'eBayPlusTransaction' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'eBayPlusTransaction'
        ],
        'GiftSummary' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\GiftSummaryType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'GiftSummary'
        ],
        'DigitalDeliverySelected' => [
            'type' => 'cbdesk\eBaySDK\MerchantData\Types\DigitalDeliverySelectedType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'DigitalDeliverySelected'
        ],
        'Gift' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Gift'
        ],
        'GuaranteedShipping' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'GuaranteedShipping'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
